### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by tiptoptom**

### CODE REVIEW

**Comment by tiptoptom** [comment]
@VincentAudibert would you merge this? :see_no_evil:

**Comment by VincentAudibert** [comment]
@tiptoptom , sure ! I'll do this before the weekend (build check & version bump & deploy) 👍 .
Are you ok with your name added to the release notes ?
🙏 As a bonus and if it suits you, the [playstore page](https://github.com/VincentAudibert/CanIDrive/issues/116#issuecomment-1126365465) would be nice to have also in german. If ok you can put the translated text in this thread (or in a dedicated issue).

**Comment by tiptoptom** [comment]
@VincentAudibert yes, you can add my name to the release notes. May in the future I will also translate the playstore page.

**Comment by tiptoptom** [comment]
@VincentAudibert any news here? :see_no_evil: 
The translated play store text is in #119

**Comment by VincentAudibert** [comment]
@tiptoptom Great for the play store text 🙏 
Regarding news, I got unfortunately (for CanIDrive) busy elsewhere about job, home & OS among others... 
Also, in the autumn, Google removed the app from the PlayStore as "mis-directing" vs app rules, then re-instated after me complaining through the closest plausible complaining form.
All this did not help, I'll try to push the updates in the coming days...

**Pull request merged**
